language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: surge
  skip_cleanup: true
  domain: offbeat-bed.surge.sh
  project: ./build/
on:
  branch: master
deploy:
  provider: firebase
  skip_cleanup: true
  token: 1/OW9ZA3aOtxonZ4SzaGCXClZ6Fd9N7S7eg4jbw8t0ulg
on:
  branch: master

# the token bit for firebase should be encrypted, but travis CLI isn't outputting the encrypted
# https://docs.travis-ci.com/user/encryption-keys/#Usage