//GENERAL action.js
export const SNACKBAR = 'SNACKBAR';
export const LOAD_APP_BEGIN = 'LOAD_APP_BEGIN';
export const LOAD_APP_SUCCESS = 'LOAD_APP_SUCCESS';

//ROOM actions

export const FIND_ROOM_BEGIN = 'FIND_ROOM_BEGIN';
export const FIND_ROOM_SUCCESS = 'FIND_ROOM_SUCCESS';
export const FIND_ROOM_FAILURE = 'FIND_ROOM_FAILURE';

export const ENTER_ROOM_BEGIN = 'ENTER_ROOM_BEGIN';
export const ENTER_ROOM_SUCCESS = 'ENTER_ROOM_SUCCESS';
export const ENTER_ROOM_FAILURE = 'ENTER_ROOM_FAILURE';

export const EXIT_ROOM_BEGIN = 'EXIT_ROOM_BEGIN';
export const EXIT_ROOM_SUCCESS = 'EXIT_ROOM_SUCCESS';
export const EXIT_ROOM_FAILURE = 'EXIT_ROOM_FAILURE';

export const CREATE_ROOM_BEGIN = 'CREATE_ROOM_BEGIN';
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS';
export const CREATE_ROOM_FAILURE = 'CREATE_ROOM_FAILURE';

export const CHANGE_ROOM_NAME_BEGIN = 'CHANGE_ROOM_NAME_BEGIN';
export const CHANGE_ROOM_NAME_SUCCESS = 'CHANGE_ROOM_NAME_SUCCESS';
export const CHANGE_ROOM_NAME_FAILURE = 'CHANGE_ROOM_NAME_FAILURE';

export const CHANGE_TIMEOUT_BEGIN = 'CHANGE_TIMEOUT_BEGIN';
export const CHANGE_TIMEOUT_SUCCESS = 'CHANGE_TIMEOUT_SUCCESS';
export const CHANGE_TIMEOUT_FAILURE = 'CHANGE_TIMEOUT_FAILURE';

export const FETCH_ROOMREQ_BEGIN = "FETCH_ROOMREQ_BEGIN";
export const FETCH_ROOMREQ_SUCCESS = "FETCH_ROOMREQ_SUCCESS";
export const FETCH_ROOMREQ_FAILURE = "FETCH_ROOMREQ_FAILURE";

export const SWITCH_TAB = 'SWITCH_TAB';

//SPOTIFY actions

export const GET_TRACK_BEGIN = 'GET_TRACK_BEGIN';
export const GET_TRACK_SUCCESS = 'GET_TRACK_SUCCESS';
export const GET_TRACK_FAILURE = 'GET_TRACK_FAILURE';

export const SEARCH_TRACK_BEGIN = 'SEARCH_TRACK_BEGIN';
export const SEARCH_TRACK_SUCCESS = 'SEARCH_TRACK_SUCCESS';
export const SEARCH_TRACK_FAILURE = 'SEARCH_TRACK_FAILURE';


//AUTH actions

export const LOGIN_BEGIN = 'LOGIN_BEGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_BEGIN = 'LOGOUT_BEGIN';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

// REQUEST actions

export const REQUEST_TRACK_BEGIN = "REQUEST_TRACK_BEGIN";
export const REQUEST_TRACK_SUCCESS = "REQUEST_TRACK_SUCCESS";
export const REQUEST_TRACK_FAILURE = "REQUEST_TRACK_FAILURE"

export const RESPOND_REQUEST_BEGIN = "RESPOND_REQUEST_BEGIN";
export const RESPOND_REQUEST_SUCCESS = "RESPOND_REQUEST_SUCCESS";
export const RESPOND_REQUEST_FAILURE = "RESPOND_REQUEST_FAILURE"

export const REFRESH_REQUESTLIST_BEGIN = "REFRESH_REQUESTLIST_BEGIN";
export const REFRESH_REQUESTLIST_SUCCESS = "REFRESH_REQUESTLIST_SUCCESS";
export const REFRESH_REQUESTLIST_FAILURE = "REFRESH_REQUESTLIST_FAILURE"

export const REMOVE_REQUEST_BEGIN = "REMOVE_REQUEST_BEGIN";
export const REMOVE_REQUEST_SUCCESS = "REMOVE_REQUEST_SUCCESS";
export const REMOVE_REQUEST_FAILURE = "REMOVE_REQUEST_FAILURE"


